### ISSUE TITLE
Add github support

### ISSUE THREAD

**Issue by ezienecker** [ezienecker/static-code-review-plugin#2]
It would be nice if you could comment GitHub Pull Request as well as GitLab Merge Request

**Comment by shubh710** [comment]
I would like to help.
What language is required for this project and what level of expertise.
I know JavaScript and completely beginner to open source.

**Comment by ManuZiD** [comment]
As you can see in the project main page this plugin is written in Kotlin. It would be nice if you‘d have a sensitivity for clean code. You can have a look at the GitLab api client implementation and adopt to the github api client.
